import { Unit, Category, Item, UnitStock, Movement, Loan, User, Request, FurnitureTransfer } from '../types';

export const units: Unit[] = [
  {
    id: 'unit-warehouse',
    name: 'Almoxarifado Central',
    address: 'Rua do Estoque, 100',
    status: 'active',
  },
  {
    id: 'unit-1',
    name: 'Paulista 302',
    address: 'Av. Paulista, 302',
    status: 'active',
  },
  {
    id: 'unit-2',
    name: 'Paulista 475',
    address: 'Av. Paulista, 475',
    status: 'active',
  },
  {
    id: 'unit-3',
    name: 'Campus 1',
    address: 'Campus 1 - Endereço',
    status: 'active',
  },
  {
    id: 'unit-4',
    name: 'Campus 2',
    address: 'Campus 2 - Endereço',
    status: 'active',
  },
  {
    id: 'unit-5',
    name: 'Consolação',
    address: 'Rua da Consolação',
    status: 'active',
  },
  {
    id: 'unit-6',
    name: 'Pinheiros 2',
    address: 'Pinheiros 2 - Endereço',
    status: 'active',
  },
  {
    id: 'unit-7',
    name: 'Joaquim Antunes',
    address: 'Rua Joaquim Antunes',
    status: 'active',
  },
  {
    id: 'unit-8',
    name: 'Amauri 1',
    address: 'Rua Amauri - Unidade 1',
    status: 'active',
  },
  {
    id: 'unit-9',
    name: 'Amauri 2',
    address: 'Rua Amauri - Unidade 2',
    status: 'active',
  },
  {
    id: 'unit-10',
    name: 'Funchal',
    address: 'Rua Funchal',
    status: 'active',
  },
];

export const categories: Category[] = [
  { id: 'cat-1', name: 'Acessórios', description: 'Cabos, adaptadores e acessórios diversos' },
  { id: 'cat-2', name: 'Áudio/Vídeo', description: 'Equipamentos de áudio e vídeo' },
  { id: 'cat-3', name: 'Ferramentas', description: 'Ferramentas e equipamentos' },
  { id: 'cat-4', name: 'Limpeza', description: 'Produtos e itens de limpeza' },
  { id: 'cat-5', name: 'Consumíveis', description: 'Café, açúcar, copos e outros itens de consumo diário' },
  { id: 'cat-6', name: 'Elétrica', description: 'Materiais elétricos e iluminação' },
  { id: 'cat-7', name: 'Hidráulica', description: 'Materiais para manutenção hidráulica' },
  { id: 'cat-8', name: 'Escritório', description: 'Material de escritório e papelaria' },
  { id: 'cat-9', name: 'Móveis', description: 'Cadeiras, mesas, armários e outros móveis' },
];

export const mockItems: Item[] = [
  {
    id: 'item-1',
    productId: 1,
    name: 'Cabo HDMI',
    categoryId: 'cat-1',
    description: 'Cabo HDMI 2.0 de alta velocidade',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 7,
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1589739900243-c8c6e1c5f3b4?w=400',
  },
  {
    id: 'item-2',
    productId: 2,
    name: 'Adaptador USB-C',
    categoryId: 'cat-1',
    description: 'Adaptador USB-C para HDMI/USB',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 7,
    active: true,
  },
  {
    id: 'item-3',
    productId: 3,
    name: 'Pilhas AA',
    categoryId: 'cat-2',
    description: 'Pilhas alcalinas AA',
    unitOfMeasure: 'pacote',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 0,
    active: true,
  },
  {
    id: 'item-4',
    productId: 4,
    name: 'Fita Adesiva',
    categoryId: 'cat-2',
    description: 'Fita adesiva transparente 50mm',
    unitOfMeasure: 'rolo',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 0,
    active: true,
  },
  {
    id: 'item-5',
    productId: 5,
    name: 'Mouse Sem Fio',
    categoryId: 'cat-1',
    description: 'Mouse wireless ergonômico',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 14,
    active: true,
    imageUrl: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400',
  },
  {
    id: 'item-6',
    productId: 6,
    name: 'Cadeado',
    categoryId: 'cat-3',
    description: 'Cadeado de segurança com chave',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 30,
    active: true,
    brand: 'Papaiz',
    model: '40mm',
  },
  {
    id: 'item-7',
    productId: 7,
    name: 'Kit de Limpeza',
    categoryId: 'cat-4',
    description: 'Kit com pano, spray e álcool',
    unitOfMeasure: 'kit',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 0,
    active: true,
  },
  {
    id: 'item-8',
    productId: 8,
    name: 'Roteador de Mesa',
    categoryId: 'cat-1',
    description: 'Roteador WiFi portátil',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 7,
    active: true,
  },
  {
    id: 'item-9',
    productId: 9,
    name: 'Café em Pó 500g',
    categoryId: 'cat-5',
    description: 'Café torrado e moído pacote 500g',
    unitOfMeasure: 'pacote',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultMinimumQuantity: 10,
    defaultLoanDays: 0,
    brand: 'Pilão',
    model: 'Tradicional',
    active: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'item-10',
    productId: 10,
    name: 'Cadeira Ergonômica',
    categoryId: 'cat-9',
    description: 'Cadeira de escritório ergonômica com apoio lombar',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1688578735427-994ecdea3ea4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-11',
    productId: 11,
    name: 'Mesa de Reunião',
    categoryId: 'cat-9',
    description: 'Mesa de reunião para 8 pessoas',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1700451761308-ec56f93c82be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-12',
    productId: 12,
    name: 'Armário Arquivos',
    categoryId: 'cat-9',
    description: 'Armário de aço para arquivos com 4 gavetas',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1569235186275-626cb53b83ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-13',
    productId: 13,
    name: 'Poltrona de Espera',
    categoryId: 'cat-9',
    description: 'Poltrona confortável para sala de espera',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1552808902-af82721d1846?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-14',
    productId: 14,
    name: 'Cabo HDMI 1 Metro',
    categoryId: 'cat-1',
    description: 'Cabo HDMI 2.0 de 1 metro',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 15,
    active: true,
    brand: 'Elg',
    model: '1m',
  },
  {
    id: 'item-15',
    productId: 15,
    name: 'Cabo HDMI 2 Metros',
    categoryId: 'cat-1',
    description: 'Cabo HDMI 2.0 de 2 metros',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 15,
    active: true,
    brand: 'Elg',
    model: '2m',
  },
  {
    id: 'item-16',
    productId: 16,
    name: 'Pilha AA',
    categoryId: 'cat-2',
    description: 'Pilha alcalina AA individual',
    unitOfMeasure: 'unidade',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 0,
    active: true,
    brand: 'Duracell',
    model: 'AA',
  },
  {
    id: 'item-17',
    productId: 17,
    name: 'Pilha AAA',
    categoryId: 'cat-2',
    description: 'Pilha alcalina AAA individual',
    unitOfMeasure: 'unidade',
    isConsumable: true,
    requiresResponsibilityTerm: false,
    defaultLoanDays: 0,
    active: true,
    brand: 'Duracell',
    model: 'AAA',
  },
  {
    id: 'item-18',
    productId: 18,
    name: 'Escrivaninha Executiva',
    categoryId: 'cat-9',
    description: 'Escrivaninha executiva com gavetas laterais',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-19',
    productId: 19,
    name: 'Estante Modular',
    categoryId: 'cat-9',
    description: 'Estante modular de 5 prateleiras',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
  {
    id: 'item-20',
    productId: 20,
    name: 'Sofá Corporativo 3 Lugares',
    categoryId: 'cat-9',
    description: 'Sofá corporativo para área de espera',
    unitOfMeasure: 'unidade',
    isConsumable: false,
    requiresResponsibilityTerm: true,
    defaultLoanDays: 0,
    active: true,
    isFurniture: true,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
  },
];

export const unitStocks: UnitStock[] = [
  // Paulista 302
  { id: 'stock-1', itemId: 'item-1', unitId: 'unit-1', quantity: 15, minimumQuantity: 10, location: 'Armário A - Prateleira 1' },
  { id: 'stock-2', itemId: 'item-2', unitId: 'unit-1', quantity: 8, minimumQuantity: 20, location: 'Armário A - Prateleira 1' },
  { id: 'stock-3', itemId: 'item-3', unitId: 'unit-1', quantity: 1, minimumQuantity: 2, location: 'Sala de AV' },
  { id: 'stock-4', itemId: 'item-4', unitId: 'unit-1', quantity: 5, minimumQuantity: 3, location: 'Armário A - Prateleira 2' },
  { id: 'stock-5', itemId: 'item-5', unitId: 'unit-1', quantity: 3, minimumQuantity: 5, location: 'Armário B - Prateleira 1' },
  { id: 'stock-6', itemId: 'item-6', unitId: 'unit-1', quantity: 10, minimumQuantity: 5, location: 'Armário C' },
  { id: 'stock-7', itemId: 'item-7', unitId: 'unit-1', quantity: 12, minimumQuantity: 8, location: 'Depósito' },
  { id: 'stock-8', itemId: 'item-8', unitId: 'unit-1', quantity: 2, minimumQuantity: 3, location: 'Armário A - Prateleira 3' },
  { id: 'stock-17', itemId: 'item-9', unitId: 'unit-1', quantity: 12, minimumQuantity: 10, location: 'Copa - Armário Superior' },
  
  // Paulista 475
  { id: 'stock-9', itemId: 'item-1', unitId: 'unit-2', quantity: 20, minimumQuantity: 10, location: 'Estoque Principal' },
  { id: 'stock-10', itemId: 'item-2', unitId: 'unit-2', quantity: 25, minimumQuantity: 20, location: 'Estoque Principal' },
  { id: 'stock-11', itemId: 'item-3', unitId: 'unit-2', quantity: 2, minimumQuantity: 1, location: 'Sala de Reuniões' },
  { id: 'stock-12', itemId: 'item-4', unitId: 'unit-2', quantity: 7, minimumQuantity: 5, location: 'Estoque Principal' },
  { id: 'stock-13', itemId: 'item-5', unitId: 'unit-2', quantity: 8, minimumQuantity: 5, location: 'Estoque Principal' },
  { id: 'stock-14', itemId: 'item-6', unitId: 'unit-2', quantity: 15, minimumQuantity: 10, location: 'Armário Segurança' },
  { id: 'stock-15', itemId: 'item-7', unitId: 'unit-2', quantity: 6, minimumQuantity: 8, location: 'Depósito' },
  { id: 'stock-16', itemId: 'item-8', unitId: 'unit-2', quantity: 4, minimumQuantity: 2, location: 'TI' },
  { id: 'stock-18', itemId: 'item-9', unitId: 'unit-2', quantity: 8, minimumQuantity: 10, location: 'Copa' },
  
  // Almoxarifado Central - maior estoque
  { id: 'stock-wh-1', itemId: 'item-1', unitId: 'unit-warehouse', quantity: 150, minimumQuantity: 50, location: 'Setor A - Prateleira 12' },
  { id: 'stock-wh-2', itemId: 'item-2', unitId: 'unit-warehouse', quantity: 200, minimumQuantity: 100, location: 'Setor A - Prateleira 13' },
  { id: 'stock-wh-3', itemId: 'item-7', unitId: 'unit-warehouse', quantity: 80, minimumQuantity: 40, location: 'Setor B - Prateleira 5' },
  { id: 'stock-wh-4', itemId: 'item-9', unitId: 'unit-warehouse', quantity: 120, minimumQuantity: 60, location: 'Setor C - Prateleira 1' },
  
  // Almoxarifado Central - Móveis para distribuição
  { id: 'stock-wh-5', itemId: 'item-10', unitId: 'unit-warehouse', quantity: 45, minimumQuantity: 20, location: 'Setor Móveis - Área 1' }, // Cadeiras
  { id: 'stock-wh-6', itemId: 'item-11', unitId: 'unit-warehouse', quantity: 12, minimumQuantity: 5, location: 'Setor Móveis - Área 2' }, // Mesas
  { id: 'stock-wh-7', itemId: 'item-12', unitId: 'unit-warehouse', quantity: 18, minimumQuantity: 8, location: 'Setor Móveis - Área 3' }, // Armários
  { id: 'stock-wh-8', itemId: 'item-13', unitId: 'unit-warehouse', quantity: 15, minimumQuantity: 6, location: 'Setor Móveis - Área 4' }, // Poltronas
  { id: 'stock-wh-14', itemId: 'item-18', unitId: 'unit-warehouse', quantity: 20, minimumQuantity: 8, location: 'Setor Móveis - Área 5' }, // Escrivaninhas
  { id: 'stock-wh-15', itemId: 'item-19', unitId: 'unit-warehouse', quantity: 25, minimumQuantity: 10, location: 'Setor Móveis - Área 6' }, // Estantes
  { id: 'stock-wh-16', itemId: 'item-20', unitId: 'unit-warehouse', quantity: 8, minimumQuantity: 3, location: 'Setor Móveis - Área 7' }, // Sofás
  
  // Móveis - Paulista 302
  { id: 'stock-19', itemId: 'item-10', unitId: 'unit-1', quantity: 25, minimumQuantity: 20, location: 'Escritório - Andar 3' },
  { id: 'stock-20', itemId: 'item-11', unitId: 'unit-1', quantity: 4, minimumQuantity: 3, location: 'Salas de Reunião' },
  { id: 'stock-21', itemId: 'item-12', unitId: 'unit-1', quantity: 8, minimumQuantity: 5, location: 'Administrativo' },
  { id: 'stock-22', itemId: 'item-13', unitId: 'unit-1', quantity: 6, minimumQuantity: 4, location: 'Recepção' },
  
  // Móveis - Paulista 475
  { id: 'stock-23', itemId: 'item-10', unitId: 'unit-2', quantity: 30, minimumQuantity: 25, location: 'Escritório - Andar 2' },
  { id: 'stock-24', itemId: 'item-11', unitId: 'unit-2', quantity: 6, minimumQuantity: 4, location: 'Salas de Reunião' },
  { id: 'stock-25', itemId: 'item-12', unitId: 'unit-2', quantity: 10, minimumQuantity: 6, location: 'Administrativo' },
  { id: 'stock-26', itemId: 'item-13', unitId: 'unit-2', quantity: 8, minimumQuantity: 5, location: 'Recepção' },
  
  // Produtos Únicos - Paulista 302
  { id: 'stock-27', itemId: 'item-6', unitId: 'unit-1', quantity: 10, minimumQuantity: 5, location: 'Armário Segurança' }, // Cadeados
  { id: 'stock-28', itemId: 'item-14', unitId: 'unit-1', quantity: 8, minimumQuantity: 5, location: 'TI - Prateleira B' }, // Cabo HDMI 1m
  { id: 'stock-29', itemId: 'item-15', unitId: 'unit-1', quantity: 5, minimumQuantity: 3, location: 'TI - Prateleira B' }, // Cabo HDMI 2m
  { id: 'stock-30', itemId: 'item-16', unitId: 'unit-1', quantity: 20, minimumQuantity: 15, location: 'Armário C - Gaveta 1' }, // Pilhas AA
  { id: 'stock-31', itemId: 'item-17', unitId: 'unit-1', quantity: 15, minimumQuantity: 10, location: 'Armário C - Gaveta 1' }, // Pilhas AAA
  
  // Produtos Únicos - Paulista 475
  { id: 'stock-32', itemId: 'item-6', unitId: 'unit-2', quantity: 12, minimumQuantity: 6, location: 'Armário Principal' }, // Cadeados
  { id: 'stock-33', itemId: 'item-14', unitId: 'unit-2', quantity: 10, minimumQuantity: 5, location: 'TI' }, // Cabo HDMI 1m
  { id: 'stock-34', itemId: 'item-15', unitId: 'unit-2', quantity: 6, minimumQuantity: 3, location: 'TI' }, // Cabo HDMI 2m
  { id: 'stock-35', itemId: 'item-16', unitId: 'unit-2', quantity: 25, minimumQuantity: 15, location: 'Depósito - Caixa 3' }, // Pilhas AA
  { id: 'stock-36', itemId: 'item-17', unitId: 'unit-2', quantity: 18, minimumQuantity: 10, location: 'Depósito - Caixa 3' }, // Pilhas AAA
  
  // Produtos Únicos - Almoxarifado Central
  { id: 'stock-wh-9', itemId: 'item-6', unitId: 'unit-warehouse', quantity: 50, minimumQuantity: 20, location: 'Setor D - Prateleira 2' }, // Cadeados
  { id: 'stock-wh-10', itemId: 'item-14', unitId: 'unit-warehouse', quantity: 40, minimumQuantity: 15, location: 'Setor E - Prateleira 1' }, // Cabo HDMI 1m
  { id: 'stock-wh-11', itemId: 'item-15', unitId: 'unit-warehouse', quantity: 30, minimumQuantity: 10, location: 'Setor E - Prateleira 2' }, // Cabo HDMI 2m
  { id: 'stock-wh-12', itemId: 'item-16', unitId: 'unit-warehouse', quantity: 100, minimumQuantity: 50, location: 'Setor F - Caixa 1' }, // Pilhas AA
  { id: 'stock-wh-13', itemId: 'item-17', unitId: 'unit-warehouse', quantity: 80, minimumQuantity: 40, location: 'Setor F - Caixa 2' }, // Pilhas AAA
];

export const users: User[] = [
  // Paulista 302 - Controladores
  {
    id: 'user-1',
    name: 'João Paulo',
    email: 'assistant6@gowork.com.br',
    role: 'controller',
    primaryUnitId: 'unit-1',
    jobTitle: 'Community Assistente',
  },
  {
    id: 'user-2',
    name: 'Beatriz Araujo',
    email: 'workflow4@gowork.com.br',
    role: 'controller',
    primaryUnitId: 'unit-1',
    jobTitle: 'Community Leader (CL)',
  },
  
  // Paulista 475 - Controladores
  {
    id: 'user-3',
    name: 'Hugo Tangerino',
    email: 'facilities3@gowork.com.br',
    role: 'controller',
    primaryUnitId: 'unit-2',
    jobTitle: 'Community Leader',
  },
  {
    id: 'user-4',
    name: 'Janaina Oliveira',
    email: 'qualidade2@gowork.com.br',
    role: 'controller',
    primaryUnitId: 'unit-2',
    jobTitle: 'Assistente',
  },
  
  // Paulista 475 - Executor
  {
    id: 'user-5',
    name: 'Caio',
    email: 'caio.eletricista@gowork.com.br',
    role: 'executor',
    primaryUnitId: 'unit-2',
    jobTitle: 'Eletricista',
  },
  
  // Paulista 475 - Developer
  {
    id: 'user-6',
    name: 'Thiago Moura',
    email: 'bpm3@gowork.com',
    role: 'developer',
    primaryUnitId: 'unit-2',
    jobTitle: 'Desenvolvedor',
  },
  
  // Almoxarifado Central
  {
    id: 'user-7',
    name: 'André Paulino',
    email: 'almoxarifado4@gowork.com.br',
    role: 'warehouse',
    primaryUnitId: 'unit-warehouse',
    warehouseType: 'storage',
    jobTitle: 'Almoxarifado Estoque',
  },
  
  // Motorista (exemplo genérico)
  {
    id: 'user-8',
    name: 'Marcelo Motorista',
    email: 'marcelo.motorista@gowork.com',
    role: 'warehouse',
    primaryUnitId: 'unit-warehouse',
    warehouseType: 'delivery',
    jobTitle: 'Motorista',
  },
  
  // Arquitetura / Design - Volantes
  {
    id: 'user-9',
    name: 'Thamires Thaylle',
    email: 'projetos4@gowork.com.br',
    role: 'designer',
    jobTitle: 'Arquitetura - Designer',
    // Volante - sem unidade fixa, pode ver todas as unidades
  },
  {
    id: 'user-10',
    name: 'Daniela Vieira',
    email: 'design4@gowork.com.br',
    role: 'designer',
    jobTitle: 'Arquitetura - Designer',
    // Volante - sem unidade fixa, pode ver todas as unidades
  },
  
  // Solicitantes - Volantes
  {
    id: 'user-11',
    name: 'Elvis Duarte',
    email: 'ti@gowork.com.br',
    role: 'requester',
    jobTitle: 'HL TI',
    // Volante - sem unidade fixa
  },
  {
    id: 'user-12',
    name: 'Angela Pisani',
    email: 'facilities5@gowork.com.br',
    role: 'requester',
    jobTitle: 'HL Copa',
    // Volante - sem unidade fixa
  },
  
  // Administrador
  {
    id: 'user-admin',
    name: 'Suhaila',
    email: 'suhaila@gowork.com.br',
    role: 'admin',
    jobTitle: 'Administrador do Sistema',
    adminType: 'units', // Admin focado em unidades operacionais
    // Admin pode acessar todas as unidades
  },
  {
    id: 'user-admin-warehouse',
    name: 'Amanda',
    email: 'amanda@gowork.com.br',
    role: 'admin',
    jobTitle: 'Administrador de Almoxarifado',
    adminType: 'warehouse', // Admin focado em almoxarifado e designers
    // Admin pode acessar almoxarifado e análises de design
  },
];

export const movements: Movement[] = [
  {
    id: 'mov-1',
    type: 'entrada',
    itemId: 'item-1',
    unitId: 'unit-1',
    quantity: 20,
    executorUserId: 'user-2',
    timestamp: new Date('2025-11-01T10:00:00'),
    reason: 'Reposição de estoque',
    documentNumber: 'NF-001234',
  },
  {
    id: 'mov-2',
    type: 'saida',
    itemId: 'item-2',
    unitId: 'unit-1',
    quantity: 2,
    executorUserId: 'user-1',
    timestamp: new Date('2025-11-02T14:30:00'),
    reason: 'Uso em sala de reunião',
  },
  {
    id: 'mov-3',
    type: 'emprestimo',
    itemId: 'item-5',
    unitId: 'unit-1',
    quantity: 1,
    executorUserId: 'user-1',
    timestamp: new Date('2025-11-03T09:00:00'),
    reason: 'Trabalho temporário home office',
  },
  // Movimentações do Caio (Eletricista - Paulista 475)
  {
    id: 'mov-4',
    type: 'saida',
    itemId: 'item-1',
    unitId: 'unit-2',
    quantity: 3,
    executorUserId: 'user-5',
    timestamp: new Date('2025-11-04T08:30:00'),
    reason: 'Instalação de monitores - Sala de Reunião 3',
    serviceOrder: 'OS-475-2301',
  },
  {
    id: 'mov-5',
    type: 'saida',
    itemId: 'item-2',
    unitId: 'unit-2',
    quantity: 4,
    executorUserId: 'user-5',
    timestamp: new Date('2025-11-05T14:00:00'),
    reason: 'Troca de pilhas em controles remotos das salas',
    serviceOrder: 'OS-475-2305',
  },
  {
    id: 'mov-6',
    type: 'saida',
    itemId: 'item-8',
    unitId: 'unit-2',
    quantity: 1,
    executorUserId: 'user-5',
    timestamp: new Date('2025-11-06T10:15:00'),
    reason: 'Configuração de rede temporária - Evento corporativo',
    serviceOrder: 'OS-475-2308',
  },
  
  // Movimentações do Almoxarifado Central
  {
    id: 'mov-wh-1',
    type: 'entrada',
    itemId: 'item-1',
    unitId: 'unit-warehouse',
    quantity: 100,
    executorUserId: 'user-7',
    timestamp: new Date('2025-10-15T09:00:00'),
    reason: 'Compra mensal de cabos HDMI',
    documentNumber: 'NF-005678',
  },
  {
    id: 'mov-wh-2',
    type: 'saida',
    itemId: 'item-1',
    unitId: 'unit-warehouse',
    quantity: 30,
    executorUserId: 'user-7',
    timestamp: new Date('2025-10-20T14:00:00'),
    reason: 'Distribuição para unidade Paulista 302',
  },
  {
    id: 'mov-wh-3',
    type: 'entrada',
    itemId: 'item-9',
    unitId: 'unit-warehouse',
    quantity: 150,
    executorUserId: 'user-7',
    timestamp: new Date('2025-10-18T10:30:00'),
    reason: 'Compra de café para todas as unidades',
    documentNumber: 'NF-005690',
  },
  {
    id: 'mov-wh-4',
    type: 'saida',
    itemId: 'item-9',
    unitId: 'unit-warehouse',
    quantity: 25,
    executorUserId: 'user-8',
    timestamp: new Date('2025-10-22T15:00:00'),
    reason: 'Entrega para Paulista 475',
  },
  {
    id: 'mov-wh-5',
    type: 'entrada',
    itemId: 'item-10',
    unitId: 'unit-warehouse',
    quantity: 50,
    executorUserId: 'user-7',
    timestamp: new Date('2025-10-25T11:00:00'),
    reason: 'Aquisição de cadeiras ergonômicas',
    documentNumber: 'NF-005705',
  },
  {
    id: 'mov-wh-6',
    type: 'saida',
    itemId: 'item-10',
    unitId: 'unit-warehouse',
    quantity: 5,
    executorUserId: 'user-8',
    timestamp: new Date('2025-10-28T09:30:00'),
    reason: 'Distribuição aprovada por designer',
  },
  {
    id: 'mov-wh-7',
    type: 'entrada',
    itemId: 'item-2',
    unitId: 'unit-warehouse',
    quantity: 200,
    executorUserId: 'user-7',
    timestamp: new Date('2025-11-01T08:00:00'),
    reason: 'Reposição de adaptadores USB-C',
    documentNumber: 'NF-005720',
  },
  {
    id: 'mov-wh-8',
    type: 'saida',
    itemId: 'item-2',
    unitId: 'unit-warehouse',
    quantity: 50,
    executorUserId: 'user-8',
    timestamp: new Date('2025-11-03T16:00:00'),
    reason: 'Entrega urgente para múltiplas unidades',
  },
  {
    id: 'mov-wh-9',
    type: 'entrada',
    itemId: 'item-7',
    unitId: 'unit-warehouse',
    quantity: 100,
    executorUserId: 'user-7',
    timestamp: new Date('2025-11-05T10:00:00'),
    reason: 'Compra de kits de limpeza',
    documentNumber: 'NF-005735',
  },
  {
    id: 'mov-wh-10',
    type: 'saida',
    itemId: 'item-7',
    unitId: 'unit-warehouse',
    quantity: 20,
    executorUserId: 'user-8',
    timestamp: new Date('2025-11-06T14:30:00'),
    reason: 'Distribuição para unidades',
  },
];

export const loans: Loan[] = [
  {
    id: 'loan-1',
    itemId: 'item-5',
    unitId: 'unit-1',
    responsibleUserId: 'user-1',
    withdrawalDate: new Date('2025-11-03T09:00:00'),
    expectedReturnDate: new Date('2025-11-10T17:00:00'),
    status: 'active',
    observations: 'Trabalho temporário home office',
  },
  {
    id: 'loan-2',
    itemId: 'item-4',
    unitId: 'unit-1',
    responsibleUserId: 'user-1',
    withdrawalDate: new Date('2025-10-28T10:00:00'),
    expectedReturnDate: new Date('2025-10-31T17:00:00'),
    status: 'overdue',
    observations: 'Adaptador para apresentação',
  },
  {
    id: 'loan-3',
    itemId: 'item-6',
    unitId: 'unit-2',
    responsibleUserId: 'user-4',
    withdrawalDate: new Date('2025-11-01T08:00:00'),
    expectedReturnDate: new Date('2025-12-01T17:00:00'),
    status: 'active',
  },
];

export const requests: Request[] = [
  {
    id: 'req-1',
    itemId: 'item-1',
    requestingUnitId: 'unit-1',
    requestedByUserId: 'user-2',
    quantity: 30,
    status: 'pending',
    createdAt: new Date('2025-11-05T10:00:00'),
    urgency: 'high',
    observations: 'Estoque baixo, necessário para reuniões da semana',
  },
  {
    id: 'req-2',
    itemId: 'item-9',
    requestingUnitId: 'unit-2',
    requestedByUserId: 'user-5',
    quantity: 20,
    status: 'approved',
    createdAt: new Date('2025-11-04T09:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-04T10:30:00'),
    urgency: 'medium',
    observations: 'Reposição mensal de café',
  },
  {
    id: 'req-3',
    itemId: 'item-7',
    requestingUnitId: 'unit-1',
    requestedByUserId: 'user-2',
    quantity: 10,
    status: 'completed',
    createdAt: new Date('2025-11-02T14:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-02T15:00:00'),
    completedByUserId: 'user-6',
    completedAt: new Date('2025-11-03T09:00:00'),
    urgency: 'low',
  },
  {
    id: 'req-4',
    itemId: 'item-2',
    requestingUnitId: 'unit-2',
    requestedByUserId: 'user-5',
    quantity: 50,
    status: 'processing',
    createdAt: new Date('2025-11-05T08:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-05T09:00:00'),
    urgency: 'high',
    observations: 'Urgente - eventos da semana',
  },
  // Solicitações dos Solicitantes Volantes
  {
    id: 'req-5',
    itemId: 'item-1',
    requestingUnitId: 'unit-1', // Destinado para Paulista 302
    requestedByUserId: 'user-11', // Elvis Duarte - HL TI
    quantity: 15,
    status: 'pending',
    createdAt: new Date('2025-11-06T14:00:00'),
    urgency: 'medium',
    observations: 'Cabos HDMI para manutenção TI em todas as salas de reunião',
  },
  {
    id: 'req-6',
    itemId: 'item-9',
    requestingUnitId: 'unit-2', // Destinado para Paulista 475
    requestedByUserId: 'user-12', // Angela Pisani - HL Copa
    quantity: 25,
    status: 'approved',
    createdAt: new Date('2025-11-05T11:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-05T13:00:00'),
    urgency: 'high',
    observations: 'Reposição urgente de café para eventos corporativos',
  },
  {
    id: 'req-7',
    itemId: 'item-7',
    requestingUnitId: 'unit-1', // Destinado para Paulista 302
    requestedByUserId: 'user-12', // Angela Pisani - HL Copa
    quantity: 8,
    status: 'completed',
    createdAt: new Date('2025-11-03T10:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-03T11:00:00'),
    completedByUserId: 'user-6',
    completedAt: new Date('2025-11-04T08:00:00'),
    urgency: 'low',
    observations: 'Kits de limpeza para área de copa',
  },
  {
    id: 'req-8',
    itemId: 'item-8',
    requestingUnitId: 'unit-2', // Destinado para Paulista 475
    requestedByUserId: 'user-11', // Elvis Duarte - HL TI
    quantity: 3,
    status: 'processing',
    createdAt: new Date('2025-11-06T09:00:00'),
    approvedByUserId: 'user-6',
    approvedAt: new Date('2025-11-06T10:00:00'),
    urgency: 'high',
    observations: 'Roteadores para expansão de rede WiFi',
  },
];

export const furnitureTransfers: FurnitureTransfer[] = [
  {
    id: 'ft-1',
    itemId: 'item-10',
    fromUnitId: 'unit-1',
    toUnitId: 'unit-2',
    requestedByUserId: 'user-8',
    status: 'pending',
    createdAt: new Date('2025-11-05T11:00:00'),
    observations: 'Necessário 3 cadeiras para novo espaço de trabalho',
  },
  {
    id: 'ft-2',
    itemId: 'item-11',
    fromUnitId: 'unit-2',
    toUnitId: 'unit-1',
    requestedByUserId: 'user-7',
    approvedByUserId: 'user-3',
    status: 'approved',
    createdAt: new Date('2025-11-04T14:00:00'),
    observations: 'Mesa para nova sala de reunião',
  },
  {
    id: 'ft-3',
    itemId: 'item-13',
    fromUnitId: 'unit-1',
    toUnitId: 'unit-2',
    requestedByUserId: 'user-8',
    approvedByUserId: 'user-3',
    status: 'completed',
    createdAt: new Date('2025-11-01T10:00:00'),
    completedAt: new Date('2025-11-02T16:00:00'),
    observations: 'Reforma da recepção',
  },
];